services:
  - type: web
    name: chator-client
    runtime: node
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 20
